window.HC_GAP_DATA_UPDATED_AT = "2026-05-11T11:40:00-03:00";
window.HC_GAP_DATA = {
  source: "Follow up orders + HC Preview V_2 / SIMULADOR PICKERS - MAIO / colunas AD:AF",
  month: "Maio",
  rows: [
    { store: "Recife Sul", plan: 10, real: 12, diff: 2 },
    { store: "Vila Madalena", plan: 25, real: 24, diff: -1 },
    { store: "Bela Vista", plan: 18, real: 14, diff: -4 },
    { store: "Vila Izabel", plan: 8, real: 9, diff: 1 },
    { store: "Alto do XV", plan: 6, real: 6, diff: 0 },
    { store: "Barra da Tijuca 2", plan: 7, real: 7, diff: 0 },
    { store: "Carrão", plan: 8, real: 9, diff: 1 },
    { store: "Aldeota", plan: 10, real: 10, diff: 0 },
    { store: "Santo Amaro", plan: 10, real: 11, diff: 1 },
    { store: "Aflitos", plan: 16, real: 15, diff: -1 },
    { store: "Barra da Tijuca 3", plan: 7, real: 5, diff: -2 },
    { store: "Alphaville", plan: 6, real: 5, diff: -1 },
    { store: "Bonfinglioli", plan: 8, real: 6, diff: -2 },
    { store: "Santo André", plan: 8, real: 8, diff: 0 },
    { store: "Santa Efigênia", plan: 11, real: 11, diff: 0 },
    { store: "Castelo", plan: 7, real: 5, diff: -2 },
    { store: "Jardins", plan: 18, real: 16, diff: -2 },
    { store: "Santana", plan: 9, real: 7, diff: -2 },
    { store: "Alto Do Ipiranga", plan: 9, real: 8, diff: -1 },
    { store: "Aclimação", plan: 9, real: 8, diff: -1 },
    { store: "PA Centro", plan: 7, real: 6, diff: -1 },
    { store: "Cambui", plan: 9, real: 7, diff: -2 },
    { store: "Moema", plan: 18, real: 16, diff: -2 },
    { store: "Estoril", plan: 11, real: 9, diff: -2 },
    { store: "Botafogo II", plan: 14, real: 14, diff: 0 },
    { store: "Vila Mascote", plan: 12, real: 7, diff: -5 },
    { store: "Vila Prudente", plan: 13, real: 10, diff: -3 },
    { store: "Lapa", plan: 10, real: 6, diff: -4 },
    { store: "Brooklin II", plan: 17, real: 15, diff: -2 },
    { store: "Santa Cecília", plan: 30, real: 25, diff: -5 },
    { store: "Vila Clementino", plan: 14, real: 10, diff: -4 },
    { store: "Catete II", plan: 8, real: 10, diff: 2 },
    { store: "Ipanema", plan: 9, real: 8, diff: -1 },
    { store: "Leblon", plan: 12, real: 10, diff: -2 },
    { store: "Nova Recreio", plan: 5, real: 6, diff: 1 },
    { store: "Tijuca", plan: 8, real: 7, diff: -1 },
    { store: "Morumbi", plan: 16, real: 17, diff: 1 },
    { store: "Vila Olimpia", plan: 26, real: 24, diff: -2 }
  ]
};
